%% Scaling from pre-images
function [Zoom2mm, Full_Im, Zoomed_Im] = PixelScalingErrFunc
%% Starting to find the edges from a zoomed out image
StartingFolder= cd;
[file,path] = uigetfile('*.tif', 'Select Image showing grip edges');
if isequal(file,0)
   disp('User selected Cancel');
else
   disp(['User selected ', fullfile(path,file)]);
   cd(path)
   Full_Im = importfile(file);
end
% Clear temporary variables
clear path file 
cd(StartingFolder) %return

dummy.half_size = 150; %assume that the sample is in the middle 300 pixels of the image
dummy.middle = round(size(Full_Im,2)./2)-dummy.half_size:round(size(Full_Im,2)./2)+dummy.half_size;
check.Sample_width = ECFedgefit(Full_Im,1,dummy.middle);
check.grip_width = ECFedgefit(Full_Im,1,1:1280);

sample_width = diff(check.Sample_width); 
grip_width = diff(check.grip_width);
Pix2mm = grip_width./30; % assumed that grip is 30 mm across this gives the number of pix in 1 mm

%% Redo for the zoomed in image to get a scaling 

StartingFolder= cd;
[file,path] = uigetfile('*.tif', 'Select Image at test Zoom');
if isequal(file,0)
   disp('User selected Cancel');
else
   disp(['User selected ', fullfile(path,file)]);
   cd(path)
   Zoomed_Im = importfile(file);
end
clear file path

dummy.half_size = 300; %assume that the sample is in the middle 600 pixels of the image
dummy.middle = round(size(Zoomed_Im,2)./2)-dummy.half_size:round(size(Zoomed_Im,2)./2)+dummy.half_size;
check.Sample_Zoomwidth = ECFedgefit(Zoomed_Im,1,dummy.middle);

sample_Zoomwidth = diff(check.Sample_Zoomwidth); 

Zoom_Scale = sample_width./sample_Zoomwidth;  % This is the ratio of the pixel sizes in Full and zoomed in.

%% This is the number of zoomed in pixel in 1 mm
Zoom2mm = Pix2mm./Zoom_Scale; 
cd(StartingFolder)
end

function rawData = importfile(fileToRead)
%  Auto-generated by MATLAB on 15-Dec-2022 15:42:21

% Import the file
rawData = importdata(fileToRead);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[~,name] = fileparts(fileToRead);
newData.(matlab.lang.makeValidName(name)) = rawData;

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData);
for i = 1:length(vars)
    assignin('base', vars{i}, newData.(vars{i}));
end
end